version: '3.8'

services:
  app:
    build: .
    image: speakr:latest
    container_name: speakr
    restart: unless-stopped
    ports:
      - "8899:8899"
    volumes:
      - speakr-uploads:/data/uploads
      - speakr-instance:/data/instance
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/instance/transcriptions.db
      - UPLOAD_FOLDER=/data/uploads
      # Admin user creation
      #- ADMIN_USERNAME=admin
      #- ADMIN_EMAIL=admin@example.com
      #- ADMIN_PASSWORD=securepassword

volumes:
  speakr-uploads:
    name: speakr-uploads
  speakr-instance:
    name: speakr-instance
